- hosts: localhost
connection: local

tasks:
- name: Create & Start Container
docker_container:
  name: mvn-web
  image: "ghcr.io/ksooo091/mvn-test-ansible:{{ lookup('env','BUILD_NUMBER') }}"
  state: started
  ports:
  - "80:8080"
